name: qdao
favicon: null
layout_spectrum: 0.5340576043818146
typography_spectrum: 0.6836921882349998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#999999'
    - '#4d4d4d'
    - '#aaaaaa'
    - '#9f9f9f'
    - '#484848'
  brandStrength: 0.75
  lightness: 0.5769301860127598
  saturation: 0.5
  rhythmicContrast: 0.2638955479487777
purpose: []
