layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.4910394
  lightness: 0.5125448
  brandColors:
    - '#004812'
    - '#FFC425'
    - '#2C683B'
    - '#C6AB28'
    - '#6F8126'
  rhythmicContrast: 0.3225806
typography_spectrum: 0.6899642
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: qdao
