name: qdao
favicon: null
layout_spectrum: 0.74473
typography_spectrum: 0.6899642
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004812'
    - '#FFC425'
    - '#2C683B'
    - '#C6AB28'
    - '#6F8126'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
