purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.8548387
  lightness: 0.25
  brandColors:
    - '#FEFEFE'
    - '#EF5D20'
    - '#070707'
    - '#F49B75'
    - '#545454'
  rhythmicContrast: 0.25
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: qdao
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1505376
layout_spectrum: 1
