typography_spectrum: 0.1505376
color:
  saturation: 0.2311828
  brandStrength: 0.8548387
  lightness: 0.4820789
  brandColors:
    - '#FEFEFE'
    - '#EF5D20'
    - '#070707'
    - '#F49B75'
    - '#545454'
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
name: Test v2 qdao
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Quy-Diem "DaddyDiem" DAO
description: 'Welcome :)'
purpose: []
