name: qdao
favicon: null
layout_spectrum: 0.5340576043818146
typography_spectrum: 0.6836921882349998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.13044368266128004
  lightness: 0.5769301860127598
  saturation: 0.08741210983134806
  rhythmicContrast: 0.2638955479487777
purpose: []
