name: qdao
favicon: null
layout_spectrum: 0.27032
typography_spectrum: 0.58771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#999999'
    - '#4d4d4d'
    - '#aaaaaa'
    - '#9f9f9f'
    - '#484848'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
